include:
  - local: .gitlab/templates/common.template.yml

stages:
  - preinstall
  - build
  - check
  - deploy

Dependencies:
  stage: preinstall
  needs: []
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh base_service

Static files:
  stage: build
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh build_service

Lint:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh lint_service

Test:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh test_service
    - scripts/cp-from-image.sh "pipeline=${PIPELINE_ID};commit=${GIT_COMMIT_HASH};service=test_service" coverage
      coverage
  artifacts:
    when: always
    reports:
      junit:
        - coverage/junit.xml

Code Style:
  stage: check
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh codestyle_service

NPM (stable):
  stage: deploy
  needs: ['Static files', 'Test', 'Lint', 'Code Style']
  interruptible: false
  allow_failure: true
  only:
    - master
  when: always
  variables:
    TAG: 'stable'
  script:
    - scripts/build.sh deploy_service

NPM (dev):
  stage: deploy
  needs: ['Static files', 'Test', 'Lint', 'Code Style']
  interruptible: false
  allow_failure: true
  except:
    - master
  when: manual
  variables:
    TAG: 'dev'
  script:
    - scripts/build.sh deploy_service

pages:
  stage: deploy
  needs: ['Dependencies']
  interruptible: true
  allow_failure: false
  script:
    - scripts/build.sh pages_service
    - scripts/cp-from-image.sh "pipeline=${PIPELINE_ID};commit=${GIT_COMMIT_HASH};service=pages_service" dist/demo
      public
  when: always
  artifacts:
    when: always
    paths:
      - public

dev:
  stage: deploy
  variables:
    CI: $CI
    BASE_HREF: 'pupakit-dev.bimeister.com'
  when: manual
  interruptible: true
  allow_failure: true
  before_script:
    - echo "$SSH_DEPLOY_KEY" > id_rsa && chmod 600 id_rsa
  script:
    - scripts/build.sh stage_deploy_service
    - ssh -i id_rsa -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ${TARGET_USER}@${TARGET_HOST}
      "docker rm -f pupakit-dev ; docker run -d -p 80:80 --name pupakit-dev $DEPLOY_IMAGE"

test:
  stage: deploy
  variables:
    CI: $CI
    BASE_HREF: 'pupakit-test.bimeister.com'
  when: manual
  interruptible: true
  allow_failure: true
  before_script:
    - echo "$SSH_DEPLOY_KEY" > id_rsa && chmod 600 id_rsa
  script:
    - scripts/build.sh stage_deploy_service
    - ssh -i id_rsa -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ${TARGET_USER}@${TARGET_HOST}
      "docker rm -f pupakit-test ; docker run -d -p 8080:80 --name pupakit-test $DEPLOY_IMAGE"
