version: '3.4'

services:
  stage_deploy_service:
    build:
      context: ./
      dockerfile: ./build/docker/stage-deploy.dockerfile
      labels:
        pipeline: ${PIPELINE_ID}
        commit: ${GIT_COMMIT_HASH}
        service: stage_deploy_service
      args:
        - BASE_HREF
    image: ${DEPLOY_IMAGE}
