version: '3.4'

services:
  pupakit_build:
    build:
      context: ./
      dockerfile: ./build/docker/build.dockerfile
    environment:
      - PKG_VERSION
      - PKG_TAG
      - PUBLISH
      - NPM_REPOSITORY_LOGIN
      - NPM_REPOSITORY_PASSWORD
      - NPM_REPOSITORY_EMAIL
      - NPM_REPOSITORY_URL

  pupakit_lint:
    build:
      context: ./
      dockerfile: ./build/docker/lint.dockerfile

  pupakit_test:
    build:
      context: ./
      dockerfile: ./build/docker/test.dockerfile

  pupakit_build-demo:
    build:
      context: ./
      dockerfile: ./build/docker/build-demo.dockerfile
      labels:
        meistersoft.build.pipeline: ${CI_PIPELINE_IID}
        meistersoft.git.commit: ${GIT_COMMIT}
        meistersoft.git.branch: ${BRANCH_NAME}
        service: pupakit_build-demo
