name: Publish projects
description: PupaKit action for publish project dist folders

runs:
  using: composite
  steps:
    - name: 'Authorize to NPM Registry'
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> ./projects/common/dist/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> ./projects/forms/dist/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> ./projects/icons/dist/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> ./projects/kit/dist/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> ./projects/overlays/dist/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> ./projects/table/dist/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> ./projects/tree/dist/.npmrc
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_DEPLOY_TOKEN}}" >> ./projects/widgets/dist/.npmrc

    - name: Publish common
      shell: bash
      run: cd projects/common/dist && npm publish --access public --tag dev && cd -

    - name: Publish forms
      shell: bash
      run: cd projects/forms/dist && npm publish --access public --tag dev && cd -

    - name: Publish icons
      shell: bash
      run: cd projects/icons/dist && npm publish --access public --tag dev && cd -

    - name: Publish kit
      shell: bash
      run: cd projects/kit/dist && npm publish --access public --tag dev && cd -

    - name: Publish overlays
      shell: bash
      run: cd projects/overlays/dist && npm publish --access public --tag dev && cd -

    - name: Publish table
      shell: bash
      run: cd projects/table/dist && npm publish --access public --tag dev && cd -

    - name: Publish tree
      shell: bash
      run: cd projects/tree/dist && npm publish --access public --tag dev && cd -

    - name: Publish widgets
      shell: bash
      run: cd projects/widgets/dist && npm publish --access public --tag dev && cd -
