name: Release Package

on:
  release:
    types: [published]

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: 'npm'

      - name: Install missing packages
        run: npm install @moonrepo/core-linux-x64-gnu --save-dev

      - name: Install dependencies by lockfile
        run: npm clean-install

      - name: Cache workspace
        uses: actions/cache@v3
        with:
          key: 'workspace:${{github.sha}}'
          path: ./

  static_files:
    name: Build Static Files
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - name: Download cached workspace
        uses: actions/cache@v3
        with:
          key: 'workspace:${{github.sha}}'
          path: ./

      - name: Download moon cache
        uses: actions/cache@v3
        with:
          key: 'moon'
          path: ./.moon/cache

      - name: Build static files
        run: npm run moon run :build

      - name: Generate report
        uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache projects
        uses: ./.github/actions/cache-dist-folders

  publish:
    name: Run publish
    runs-on: ubuntu-latest
    needs: [static_files]
    steps:
      - name: Download cached workspace
        uses: actions/cache@v3
        with:
          key: 'workspace:${{github.sha}}'
          path: ./

      - name: Download cached projects
        uses: ./.github/actions/cache-dist-folders

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 18.16.1

      - name: Do prepublish
        run: |
          export VERSION=${{ github.event.release.tag_name }}
          npm run build:prepublish

      - name: Publish projects
        uses: ./.github/actions/publish-projects
        with:
          token: ${{secrets.NPM_DEPLOY_TOKEN}}
          tag: latest
