name: Run Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - $default-branch

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install missing packages
        run: npm install @moonrepo/core-linux-x64-gnu

      - name: Install dependencies by lockfile
        run: npm clean-install

      - name: Share prepared workspace with other jobs
        uses: actions/cache@v3
        with:
          key: 'workspace:${{github.sha}}'
          path: ./

  static_files:
    name: Build Static Files
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - name: Download prepared workspace
        uses: actions/cache@v3
        with:
          key: 'workspace:${{github.sha}}'
          path: ./

      - name: Build static files with checks
        run: npm run moon ci

      - name: Generate report
        uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
